language: python
cache: pip
sudo: required
services:
  - docker
os:
  - linux
python:
  - "3.6"
script:
  - pip install -U pip pipenv
  - pipenv install --dev
  - pipenv run pytest --cov=metadata --cov-report=term-missing metadata
after_success:
  - coveralls
  - "./tests/lint.sh metadata"
  - "./tests/style.sh metadata"
  - "./tests/type-check.sh metadata"
